name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

        
      - name: Build Docker image
        run: docker build -t my-webapp .

      - name: Login to Docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker tag my-webapp $DOCKER_USERNAME/my-webapp:latest
          docker push $DOCKER_USERNAME/my-webapp:latest

      - name: Deploy to Server (via SSH)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-webapp:latest
            docker stop my-webapp || true
            docker rm my-webapp || true
            docker run -d -p 80:3002 --name my-webapp ${{ secrets.DOCKER_USERNAME }}/my-webapp:latest
