name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      #  List files for debugging (optional)
      - name: List repo files
        run: ls -R

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: muneebdock12/my-webapp:latest

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'
          kubeconfig: ${{ secrets.KUBECONFIG }}

      # Apply Kubernetes manifests
      - name: Deploy to Kubernetes
        run: |
          # Ensure files exist
          if [ ! -f "kubernetes/deployment.yaml" ]; then
            echo "Error: deployment.yaml not found!"
            exit 1
          fi
          if [ ! -f "kubernetes/service.yaml" ]; then
            echo "Error: service.yaml not found!"
            exit 1
          fi

          # Apply manifests
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
